import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { PurchaseItem } from '@/lib/hooks/use-purchases';
import { CatalogItem, CatalogSupplier } from '@/lib/hooks/use-catalog';

interface SupplierGroup {
  supplier: string;
  items: PurchaseItem[];
  totalQty: number;
}

// Accent color per supplier (fallback to a neutral blue)
const SUPPLIER_ACCENT: Record<string, string> = {
  'Fresh Farms': '#2E7D32',
  'Prime Meats Co': '#AD1457',
  'Ocean Catch': '#1565C0',
  'Valley Dairy': '#E65100',
  'Metro Supply': '#6A1B9A',
  'Drinks Direct': '#00838F',
  CleanPro: '#37474F',
};

function buildHtml(groups: SupplierGroup[], orderDate: string, customer?: string): string {
  const supplierBlocks = groups
    .map((group) => {
      const accent = SUPPLIER_ACCENT[group.supplier] ?? '#2563EB';
      const rows = group.items
        .map(
          (item, i) => `
          <tr style="background:${i % 2 === 0 ? '#ffffff' : '#f9fafb'}">
            <td style="padding:10px 14px;font-size:14px;color:#111827;border-bottom:1px solid #e5e7eb;">${item.name}</td>
            <td style="padding:10px 14px;font-size:14px;color:#374151;border-bottom:1px solid #e5e7eb;text-align:center;">${item.unit}</td>
            <td style="padding:10px 14px;font-size:15px;font-weight:700;color:#111827;border-bottom:1px solid #e5e7eb;text-align:center;">${item.quantity}</td>
          </tr>`
        )
        .join('');

      return `
      <div style="margin-bottom:32px;border-radius:12px;overflow:hidden;border:1px solid #e5e7eb;box-shadow:0 1px 4px rgba(0,0,0,0.06);">
        <!-- Supplier header -->
        <div style="background:${accent};padding:14px 18px;display:flex;align-items:center;justify-content:space-between;">
          <div>
            <div style="color:#ffffff;font-size:17px;font-weight:700;letter-spacing:0.2px;">${group.supplier}</div>
            <div style="color:rgba(255,255,255,0.75);font-size:12px;margin-top:3px;">${group.items.length} item${group.items.length !== 1 ? 's' : ''} &nbsp;·&nbsp; ${group.totalQty} total qty</div>
          </div>
        </div>
        <!-- Table -->
        <table style="width:100%;border-collapse:collapse;background:#ffffff;">
          <thead>
            <tr style="background:#f3f4f6;">
              <th style="padding:9px 14px;font-size:11px;font-weight:600;color:#6b7280;text-align:left;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid #e5e7eb;">Item</th>
              <th style="padding:9px 14px;font-size:11px;font-weight:600;color:#6b7280;text-align:center;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid #e5e7eb;">Unit</th>
              <th style="padding:9px 14px;font-size:11px;font-weight:600;color:#6b7280;text-align:center;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid #e5e7eb;">Qty</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>
      </div>`;
    })
    .join('');

  const totalItems = groups.reduce((s, g) => s + g.items.length, 0);
  const totalQty = groups.reduce((s, g) => s + g.totalQty, 0);

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; background: #f8fafc; padding: 32px 28px; color: #111827; }
  </style>
</head>
<body>
  <!-- Page header -->
  <div style="display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:28px;">
    <div>
      <div style="font-size:26px;font-weight:800;color:#111827;letter-spacing:-0.5px;">Purchase Order</div>
      <div style="font-size:13px;color:#6b7280;margin-top:4px;">${orderDate}</div>
      ${customer ? `<div style="font-size:15px;font-weight:600;color:#111827;margin-top:6px;">For: ${customer}</div>` : ''}
    </div>
    <div style="text-align:right;">
      <div style="font-size:13px;color:#6b7280;">${groups.length} supplier${groups.length !== 1 ? 's' : ''}</div>
      <div style="font-size:13px;color:#6b7280;">${totalItems} items &nbsp;·&nbsp; ${totalQty} total qty</div>
    </div>
  </div>

  <hr style="border:none;border-top:2px solid #e5e7eb;margin-bottom:28px;"/>

  ${supplierBlocks}

  <!-- Footer -->
  <div style="margin-top:24px;padding-top:16px;border-top:1px solid #e5e7eb;text-align:center;font-size:11px;color:#9ca3af;">
    Generated by Purchasing App
  </div>
</body>
</html>`;
}

export async function exportSupplierPDF(
  supplier: string,
  items: PurchaseItem[],
  accentColor?: string,
): Promise<void> {
  if (items.length === 0) return;

  const accent = accentColor ?? SUPPLIER_ACCENT[supplier] ?? '#2563EB';
  const totalQty = items.reduce((s, i) => s + i.quantity, 0);

  const orderDate = new Date().toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
  });

  const rows = items
    .map(
      (item, i) => `
      <tr style="background:${i % 2 === 0 ? '#ffffff' : '#f9fafb'}">
        <td style="padding:10px 14px;font-size:14px;color:#111827;border-bottom:1px solid #e5e7eb;">${item.name}</td>
        <td style="padding:10px 14px;font-size:14px;color:#374151;border-bottom:1px solid #e5e7eb;text-align:center;">${item.unit}</td>
        <td style="padding:10px 14px;font-size:15px;font-weight:700;color:#111827;border-bottom:1px solid #e5e7eb;text-align:center;">${item.quantity}</td>
      </tr>`
    )
    .join('');

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; background: #f8fafc; padding: 32px 28px; color: #111827; }
  </style>
</head>
<body>
  <div style="display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:28px;">
    <div>
      <div style="font-size:26px;font-weight:800;color:#111827;letter-spacing:-0.5px;">Purchase Order</div>
      <div style="font-size:18px;font-weight:600;color:${accent};margin-top:6px;">${supplier}</div>
      <div style="font-size:13px;color:#6b7280;margin-top:4px;">${orderDate}</div>
    </div>
    <div style="text-align:right;">
      <div style="font-size:13px;color:#6b7280;">${items.length} item${items.length !== 1 ? 's' : ''}</div>
      <div style="font-size:13px;color:#6b7280;">${totalQty} total qty</div>
    </div>
  </div>
  <hr style="border:none;border-top:2px solid #e5e7eb;margin-bottom:28px;"/>
  <div style="border-radius:12px;overflow:hidden;border:1px solid #e5e7eb;box-shadow:0 1px 4px rgba(0,0,0,0.06);">
    <div style="background:${accent};padding:14px 18px;">
      <div style="color:#ffffff;font-size:17px;font-weight:700;">${supplier}</div>
      <div style="color:rgba(255,255,255,0.75);font-size:12px;margin-top:3px;">${items.length} item${items.length !== 1 ? 's' : ''} &nbsp;·&nbsp; ${totalQty} total qty</div>
    </div>
    <table style="width:100%;border-collapse:collapse;background:#ffffff;">
      <thead>
        <tr style="background:#f3f4f6;">
          <th style="padding:9px 14px;font-size:11px;font-weight:600;color:#6b7280;text-align:left;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid #e5e7eb;">Item</th>
          <th style="padding:9px 14px;font-size:11px;font-weight:600;color:#6b7280;text-align:center;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid #e5e7eb;">Unit</th>
          <th style="padding:9px 14px;font-size:11px;font-weight:600;color:#6b7280;text-align:center;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid #e5e7eb;">Qty</th>
        </tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>
  </div>
  <div style="margin-top:24px;padding-top:16px;border-top:1px solid #e5e7eb;text-align:center;font-size:11px;color:#9ca3af;">
    Generated by Purchasing App
  </div>
</body>
</html>`;

  const { uri } = await Print.printToFileAsync({ html, base64: false });
  const canShare = await Sharing.isAvailableAsync();
  if (canShare) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      UTI: 'com.adobe.pdf',
      dialogTitle: `Export ${supplier} Order`,
    });
  }
}

export async function exportOrderPDF(items: PurchaseItem[], customer?: string): Promise<void> {
  if (items.length === 0) return;

  // Group by supplier
  const grouped: Record<string, PurchaseItem[]> = {};
  for (const item of items) {
    if (!grouped[item.supplier]) grouped[item.supplier] = [];
    grouped[item.supplier].push(item);
  }

  const groups: SupplierGroup[] = Object.entries(grouped)
    .map(([supplier, supplierItems]) => ({
      supplier,
      items: supplierItems,
      totalQty: supplierItems.reduce((s, i) => s + i.quantity, 0),
    }))
    .sort((a, b) => a.supplier.localeCompare(b.supplier));

  const orderDate = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const html = buildHtml(groups, orderDate, customer);

  const { uri } = await Print.printToFileAsync({ html, base64: false });

  const canShare = await Sharing.isAvailableAsync();
  if (canShare) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      UTI: 'com.adobe.pdf',
      dialogTitle: 'Export Purchase Order',
    });
  }
}

export async function exportCompactOrderPDF(
  items: PurchaseItem[],
  orderName: string,
  customer?: string,
): Promise<void> {
  if (items.length === 0) return;

  // Group by supplier
  const grouped: Record<string, PurchaseItem[]> = {};
  for (const item of items) {
    if (!grouped[item.supplier]) grouped[item.supplier] = [];
    grouped[item.supplier].push(item);
  }

  const groups: SupplierGroup[] = Object.entries(grouped)
    .map(([supplier, supplierItems]) => ({
      supplier,
      items: supplierItems,
      totalQty: supplierItems.reduce((s, i) => s + i.quantity, 0),
    }))
    .sort((a, b) => a.supplier.localeCompare(b.supplier));

  const orderDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  const totalItems = groups.reduce((s, g) => s + g.items.length, 0);
  const totalQty = groups.reduce((s, g) => s + g.totalQty, 0);

  // Build each supplier table cell — now handled inline in the HTML template below

  // expo-print renders HTML in a WebView and paginates by content height.
  // To force a single landscape page we must hard-clamp the root to exactly
  // the PDF canvas size (842 × 595 CSS px = A4 landscape at 72dpi) and set
  // overflow:hidden so nothing bleeds onto a second page.
  const PAGE_W = 842;
  const PAGE_H = 595;
  const PAD = 18; // px padding inside the page
  const HEADER_H = 34; // px for the title row + divider
  const FOOTER_H = 18;
  const GRID_H = PAGE_H - PAD * 2 - HEADER_H - FOOTER_H - 6; // available for tables

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    html, body {
      width: ${PAGE_W}px;
      height: ${PAGE_H}px;
      overflow: hidden;
      font-family: -apple-system, Helvetica, Arial, sans-serif;
      background: #ffffff;
      color: #111827;
    }
    .page {
      width: ${PAGE_W}px;
      height: ${PAGE_H}px;
      padding: ${PAD}px;
      overflow: hidden;
      display: flex;
      flex-direction: column;
    }
    .header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding-bottom: 7px;
      border-bottom: 2px solid #111827;
      flex-shrink: 0;
      height: ${HEADER_H}px;
    }
    .grid {
      display: flex;
      flex-direction: row;
      gap: 8px;
      flex: 1;
      overflow: hidden;
      margin-top: 6px;
    }
    .col {
      flex: 1;
      display: flex;
      flex-direction: column;
      gap: 8px;
      overflow: hidden;
      min-width: 0;
    }
    .supplier-box {
      border: 1px solid #e5e7eb;
      border-radius: 6px;
      overflow: hidden;
      flex-shrink: 0;
    }
    .supplier-header {
      padding: 4px 8px;
      display: flex;
      align-items: center;
      justify-content: space-between;
    }
    .s-name { color: #fff; font-size: 10px; font-weight: 700; }
    .s-meta { color: rgba(255,255,255,0.85); font-size: 8.5px; }
    table { width: 100%; border-collapse: collapse; background: #fff; }
    thead tr { background: #f3f4f6; }
    th {
      padding: 3px 6px;
      font-size: 7.5px;
      font-weight: 600;
      color: #6b7280;
      text-transform: uppercase;
      letter-spacing: 0.3px;
      border-bottom: 1px solid #e5e7eb;
    }
    th.left { text-align: left; }
    th.center { text-align: center; width: 36px; }
    td { padding: 3px 6px; font-size: 9px; border-bottom: 1px solid #f3f4f6; }
    td.name { color: #111827; }
    td.unit { color: #6b7280; text-align: center; white-space: nowrap; }
    td.qty { color: #111827; font-weight: 700; text-align: center; }
    .footer {
      flex-shrink: 0;
      text-align: center;
      font-size: 7.5px;
      color: #9ca3af;
      padding-top: 4px;
      border-top: 1px solid #e5e7eb;
      margin-top: 4px;
      height: ${FOOTER_H}px;
    }
  </style>
</head>
<body>
<div class="page">
  <div class="header">
    <div>
      <span style="font-size:15px;font-weight:800;letter-spacing:-0.3px;">Purchase Order</span>
      <span style="font-size:9.5px;color:#6b7280;margin-left:10px;">${orderName} &nbsp;·&nbsp; ${orderDate}${customer ? ` &nbsp;·&nbsp; For: ${customer}` : ''}</span>
    </div>
    <div style="font-size:9.5px;color:#6b7280;">
      ${groups.length} supplier${groups.length !== 1 ? 's' : ''} &nbsp;·&nbsp; ${totalItems} items &nbsp;·&nbsp; ${totalQty} total qty
    </div>
  </div>

  <div class="grid">
    ${(() => {
      // Distribute suppliers across 3 columns left-to-right
      const cols = 3;
      const columns: SupplierGroup[][] = Array.from({ length: cols }, () => []);
      groups.forEach((g, i) => columns[i % cols].push(g));
      return columns.map((colGroups) => {
        if (colGroups.length === 0) return '<div class="col"></div>';
        const boxes = colGroups.map((group) => {
          const accent = SUPPLIER_ACCENT[group.supplier] ?? '#2563EB';
          const rows = group.items.map((item, i) => `
            <tr style="background:${i % 2 === 0 ? '#fff' : '#f9fafb'}">
              <td class="name">${item.name}</td>
              <td class="unit">${item.unit}</td>
              <td class="qty">${item.quantity}</td>
            </tr>`).join('');
          return `
          <div class="supplier-box">
            <div class="supplier-header" style="background:${accent};">
              <span class="s-name">${group.supplier}</span>
              <span class="s-meta">${group.items.length} · ${group.totalQty} qty</span>
            </div>
            <table>
              <thead><tr>
                <th class="left">Item</th>
                <th class="center">Unit</th>
                <th class="center">Qty</th>
              </tr></thead>
              <tbody>${rows}</tbody>
            </table>
          </div>`;
        }).join('');
        return `<div class="col">${boxes}</div>`;
      }).join('');
    })()}
  </div>

  <div class="footer">Generated by Purchasing App</div>
</div>
</body>
</html>`;

  const { uri } = await Print.printToFileAsync({
    html,
    base64: false,
    width: PAGE_W,
    height: PAGE_H,
  });

  const canShare = await Sharing.isAvailableAsync();
  if (canShare) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      UTI: 'com.adobe.pdf',
      dialogTitle: 'Print / Export Compact Order',
    });
  }
}

export async function exportCatalogPDF(
  suppliers: CatalogSupplier[],
  items: CatalogItem[]
): Promise<void> {
  if (suppliers.length === 0) return;

  const date = new Date().toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
  });

  const totalItems = items.length;

  const supplierBlocks = suppliers
    .map((supplier) => {
      const supplierItems = items.filter((i) => i.supplierId === supplier.id);
      if (supplierItems.length === 0) return '';

      const accent = supplier.color ?? '#2563EB';
      const rows = supplierItems
        .map(
          (item, i) => `
          <tr style="background:${i % 2 === 0 ? '#ffffff' : '#f9fafb'}">
            <td style="padding:10px 14px;font-size:14px;color:#111827;border-bottom:1px solid #e5e7eb;">${item.name}</td>
            <td style="padding:10px 14px;font-size:13px;color:#6b7280;border-bottom:1px solid #e5e7eb;text-align:center;">${item.category}</td>
            <td style="padding:10px 14px;font-size:13px;color:#374151;border-bottom:1px solid #e5e7eb;text-align:center;">${item.unit}</td>
            <td style="padding:10px 14px;font-size:14px;border-bottom:1px solid #e5e7eb;text-align:center;">
              <div style="width:60px;height:20px;border-bottom:1.5px solid #d1d5db;display:inline-block;"></div>
            </td>
          </tr>`
        )
        .join('');

      return `
      <div style="margin-bottom:32px;border-radius:12px;overflow:hidden;border:1px solid #e5e7eb;box-shadow:0 1px 4px rgba(0,0,0,0.06);">
        <div style="background:${accent};padding:14px 18px;">
          <div style="color:#ffffff;font-size:17px;font-weight:700;">${supplier.name}</div>
          <div style="color:rgba(255,255,255,0.75);font-size:12px;margin-top:3px;">${supplierItems.length} item${supplierItems.length !== 1 ? 's' : ''}</div>
        </div>
        <table style="width:100%;border-collapse:collapse;background:#ffffff;">
          <thead>
            <tr style="background:#f3f4f6;">
              <th style="padding:9px 14px;font-size:11px;font-weight:600;color:#6b7280;text-align:left;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid #e5e7eb;">Item</th>
              <th style="padding:9px 14px;font-size:11px;font-weight:600;color:#6b7280;text-align:center;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid #e5e7eb;">Category</th>
              <th style="padding:9px 14px;font-size:11px;font-weight:600;color:#6b7280;text-align:center;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid #e5e7eb;">Unit</th>
              <th style="padding:9px 14px;font-size:11px;font-weight:600;color:#6b7280;text-align:center;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid #e5e7eb;">Order Qty</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>
      </div>`;
    })
    .join('');

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; background: #f8fafc; padding: 32px 28px; color: #111827; }
  </style>
</head>
<body>
  <div style="display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:28px;">
    <div>
      <div style="font-size:26px;font-weight:800;color:#111827;letter-spacing:-0.5px;">Reorder Sheet</div>
      <div style="font-size:13px;color:#6b7280;margin-top:4px;">${date}</div>
    </div>
    <div style="text-align:right;">
      <div style="font-size:13px;color:#6b7280;">${suppliers.length} supplier${suppliers.length !== 1 ? 's' : ''}</div>
      <div style="font-size:13px;color:#6b7280;">${totalItems} items total</div>
    </div>
  </div>
  <hr style="border:none;border-top:2px solid #e5e7eb;margin-bottom:28px;"/>
  ${supplierBlocks}
  <div style="margin-top:24px;padding-top:16px;border-top:1px solid #e5e7eb;text-align:center;font-size:11px;color:#9ca3af;">
    Generated by Purchasing App
  </div>
</body>
</html>`;

  const { uri } = await Print.printToFileAsync({ html, base64: false });
  const canShare = await Sharing.isAvailableAsync();
  if (canShare) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      UTI: 'com.adobe.pdf',
      dialogTitle: 'Export Reorder Sheet',
    });
  }
}
