import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { PurchaseItem } from '@/lib/hooks/use-purchases';
import { CatalogItem, CatalogSupplier } from '@/lib/hooks/use-catalog';

interface SupplierGroup {
  supplier: string;
  items: PurchaseItem[];
  totalQty: number;
}

// Accent color per supplier (fallback to a neutral blue)
const SUPPLIER_ACCENT: Record<string, string> = {
  'Fresh Farms': '#2E7D32',
  'Prime Meats Co': '#AD1457',
  'Ocean Catch': '#1565C0',
  'Valley Dairy': '#E65100',
  'Metro Supply': '#6A1B9A',
  'Drinks Direct': '#00838F',
  CleanPro: '#37474F',
};

function buildHtml(groups: SupplierGroup[], orderDate: string): string {
  const supplierBlocks = groups
    .map((group) => {
      const accent = SUPPLIER_ACCENT[group.supplier] ?? '#2563EB';
      const rows = group.items
        .map(
          (item, i) => `
          <tr style="background:${i % 2 === 0 ? '#ffffff' : '#f9fafb'}">
            <td style="padding:10px 14px;font-size:14px;color:#111827;border-bottom:1px solid #e5e7eb;">${item.name}</td>
            <td style="padding:10px 14px;font-size:14px;color:#374151;border-bottom:1px solid #e5e7eb;text-align:center;">${item.unit}</td>
            <td style="padding:10px 14px;font-size:15px;font-weight:700;color:#111827;border-bottom:1px solid #e5e7eb;text-align:center;">${item.quantity}</td>
          </tr>`
        )
        .join('');

      return `
      <div style="margin-bottom:32px;border-radius:12px;overflow:hidden;border:1px solid #e5e7eb;box-shadow:0 1px 4px rgba(0,0,0,0.06);">
        <!-- Supplier header -->
        <div style="background:${accent};padding:14px 18px;display:flex;align-items:center;justify-content:space-between;">
          <div>
            <div style="color:#ffffff;font-size:17px;font-weight:700;letter-spacing:0.2px;">${group.supplier}</div>
            <div style="color:rgba(255,255,255,0.75);font-size:12px;margin-top:3px;">${group.items.length} item${group.items.length !== 1 ? 's' : ''} &nbsp;·&nbsp; ${group.totalQty} total qty</div>
          </div>
        </div>
        <!-- Table -->
        <table style="width:100%;border-collapse:collapse;background:#ffffff;">
          <thead>
            <tr style="background:#f3f4f6;">
              <th style="padding:9px 14px;font-size:11px;font-weight:600;color:#6b7280;text-align:left;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid #e5e7eb;">Item</th>
              <th style="padding:9px 14px;font-size:11px;font-weight:600;color:#6b7280;text-align:center;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid #e5e7eb;">Unit</th>
              <th style="padding:9px 14px;font-size:11px;font-weight:600;color:#6b7280;text-align:center;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid #e5e7eb;">Qty</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>
      </div>`;
    })
    .join('');

  const totalItems = groups.reduce((s, g) => s + g.items.length, 0);
  const totalQty = groups.reduce((s, g) => s + g.totalQty, 0);

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; background: #f8fafc; padding: 32px 28px; color: #111827; }
  </style>
</head>
<body>
  <!-- Page header -->
  <div style="display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:28px;">
    <div>
      <div style="font-size:26px;font-weight:800;color:#111827;letter-spacing:-0.5px;">Purchase Order</div>
      <div style="font-size:13px;color:#6b7280;margin-top:4px;">${orderDate}</div>
    </div>
    <div style="text-align:right;">
      <div style="font-size:13px;color:#6b7280;">${groups.length} supplier${groups.length !== 1 ? 's' : ''}</div>
      <div style="font-size:13px;color:#6b7280;">${totalItems} items &nbsp;·&nbsp; ${totalQty} total qty</div>
    </div>
  </div>

  <hr style="border:none;border-top:2px solid #e5e7eb;margin-bottom:28px;"/>

  ${supplierBlocks}

  <!-- Footer -->
  <div style="margin-top:24px;padding-top:16px;border-top:1px solid #e5e7eb;text-align:center;font-size:11px;color:#9ca3af;">
    Generated by Purchasing App
  </div>
</body>
</html>`;
}

export async function exportOrderPDF(items: PurchaseItem[]): Promise<void> {
  if (items.length === 0) return;

  // Group by supplier
  const grouped: Record<string, PurchaseItem[]> = {};
  for (const item of items) {
    if (!grouped[item.supplier]) grouped[item.supplier] = [];
    grouped[item.supplier].push(item);
  }

  const groups: SupplierGroup[] = Object.entries(grouped)
    .map(([supplier, supplierItems]) => ({
      supplier,
      items: supplierItems,
      totalQty: supplierItems.reduce((s, i) => s + i.quantity, 0),
    }))
    .sort((a, b) => a.supplier.localeCompare(b.supplier));

  const orderDate = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const html = buildHtml(groups, orderDate);

  const { uri } = await Print.printToFileAsync({ html, base64: false });

  const canShare = await Sharing.isAvailableAsync();
  if (canShare) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      UTI: 'com.adobe.pdf',
      dialogTitle: 'Export Purchase Order',
    });
  }
}

export async function exportCatalogPDF(
  suppliers: CatalogSupplier[],
  items: CatalogItem[]
): Promise<void> {
  if (suppliers.length === 0) return;

  const date = new Date().toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
  });

  const totalItems = items.length;

  const supplierBlocks = suppliers
    .map((supplier) => {
      const supplierItems = items.filter((i) => i.supplierId === supplier.id);
      if (supplierItems.length === 0) return '';

      const accent = supplier.color ?? '#2563EB';
      const rows = supplierItems
        .map(
          (item, i) => `
          <tr style="background:${i % 2 === 0 ? '#ffffff' : '#f9fafb'}">
            <td style="padding:10px 14px;font-size:14px;color:#111827;border-bottom:1px solid #e5e7eb;">${item.name}</td>
            <td style="padding:10px 14px;font-size:13px;color:#6b7280;border-bottom:1px solid #e5e7eb;text-align:center;">${item.category}</td>
            <td style="padding:10px 14px;font-size:13px;color:#374151;border-bottom:1px solid #e5e7eb;text-align:center;">${item.unit}</td>
            <td style="padding:10px 14px;font-size:14px;border-bottom:1px solid #e5e7eb;text-align:center;">
              <div style="width:60px;height:20px;border-bottom:1.5px solid #d1d5db;display:inline-block;"></div>
            </td>
          </tr>`
        )
        .join('');

      return `
      <div style="margin-bottom:32px;border-radius:12px;overflow:hidden;border:1px solid #e5e7eb;box-shadow:0 1px 4px rgba(0,0,0,0.06);">
        <div style="background:${accent};padding:14px 18px;">
          <div style="color:#ffffff;font-size:17px;font-weight:700;">${supplier.name}</div>
          <div style="color:rgba(255,255,255,0.75);font-size:12px;margin-top:3px;">${supplierItems.length} item${supplierItems.length !== 1 ? 's' : ''}</div>
        </div>
        <table style="width:100%;border-collapse:collapse;background:#ffffff;">
          <thead>
            <tr style="background:#f3f4f6;">
              <th style="padding:9px 14px;font-size:11px;font-weight:600;color:#6b7280;text-align:left;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid #e5e7eb;">Item</th>
              <th style="padding:9px 14px;font-size:11px;font-weight:600;color:#6b7280;text-align:center;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid #e5e7eb;">Category</th>
              <th style="padding:9px 14px;font-size:11px;font-weight:600;color:#6b7280;text-align:center;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid #e5e7eb;">Unit</th>
              <th style="padding:9px 14px;font-size:11px;font-weight:600;color:#6b7280;text-align:center;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid #e5e7eb;">Order Qty</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>
      </div>`;
    })
    .join('');

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; background: #f8fafc; padding: 32px 28px; color: #111827; }
  </style>
</head>
<body>
  <div style="display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:28px;">
    <div>
      <div style="font-size:26px;font-weight:800;color:#111827;letter-spacing:-0.5px;">Reorder Sheet</div>
      <div style="font-size:13px;color:#6b7280;margin-top:4px;">${date}</div>
    </div>
    <div style="text-align:right;">
      <div style="font-size:13px;color:#6b7280;">${suppliers.length} supplier${suppliers.length !== 1 ? 's' : ''}</div>
      <div style="font-size:13px;color:#6b7280;">${totalItems} items total</div>
    </div>
  </div>
  <hr style="border:none;border-top:2px solid #e5e7eb;margin-bottom:28px;"/>
  ${supplierBlocks}
  <div style="margin-top:24px;padding-top:16px;border-top:1px solid #e5e7eb;text-align:center;font-size:11px;color:#9ca3af;">
    Generated by Purchasing App
  </div>
</body>
</html>`;

  const { uri } = await Print.printToFileAsync({ html, base64: false });
  const canShare = await Sharing.isAvailableAsync();
  if (canShare) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      UTI: 'com.adobe.pdf',
      dialogTitle: 'Export Reorder Sheet',
    });
  }
}
